// Code generated by "stringer -type=BlockType"; DO NOT EDIT.

package zstd

import "strconv"

const _BlockType_name = "BlockTypeRawBlockTypeRLEBlockTypeCompressedBlockTypeReserved"

var _BlockType_index = [...]uint8{0, 12, 24, 43, 60}

func (i BlockType) String() string {
	if i >= BlockType(len(_BlockType_index)-1) {
		return "BlockType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BlockType_name[_BlockType_index[i]:_BlockType_index[i+1]]
}
