// Code generated by command: go run gen_fse.go -out ../fse_decoder.s -arch amd64,arm64 -pkg=zstd. DO NOT EDIT.

//go:build !appengine && !noasm && gc && !noasm

// func buildDtable_asm(s *fseDecoder, ctx *buildDtableAsmContext) int
TEXT ·buildDtable_asm(SB), $0-24
	MOVQ ctx+8(FP), CX
	MOVQ s+0(FP), R8

	// Load values
	MOVBQZX 4098(R8), DX
	XORQ    AX, AX
	BTSQ    DX, AX
	MOVQ    (CX), BX
	MOVQ    16(CX), SI
	MOVQ    24(CX), DI
	LEAQ    -1(AX), R9
	MOVQ    8(CX), CX
	MOVWQZX 4096(R8), R8

	// End load values
	// Init, lay down lowprob symbols
	XORQ R10, R10
	JMP  init_main_loop_condition

init_main_loop:
	MOVWQSX (CX)(R10*2), R11
	CMPW    R11, $-1
	JNE     do_not_update_high_threshold
	MOVB    R10, 1(SI)(R9*8)
	DECQ    R9
	MOVQ    $0x0000000000000001, R11

do_not_update_high_threshold:
	MOVW R11, (BX)(R10*2)
	INCQ R10

init_main_loop_condition:
	CMPQ R10, R8
	JL   init_main_loop

	// Spread symbols
	// Calculate table step
	MOVQ AX, R10
	SHRQ $0x01, R10
	MOVQ AX, R11
	SHRQ $0x03, R11
	LEAQ 3(R10)(R11*1), R10

	// Fill add bits values
	LEAQ -1(AX), R11
	XORQ R12, R12
	XORQ R13, R13
	JMP  spread_main_loop_condition

spread_main_loop:
	XORQ    R14, R14
	MOVWQSX (CX)(R13*2), R15
	JMP     spread_inner_loop_condition

spread_inner_loop:
	MOVB R13, 1(SI)(R12*8)

adjust_position:
	ADDQ R10, R12
	ANDQ R11, R12
	CMPQ R12, R9
	JG   adjust_position
	INCQ R14

spread_inner_loop_condition:
	CMPQ R14, R15
	JL   spread_inner_loop
	INCQ R13

spread_main_loop_condition:
	CMPQ  R13, R8
	JL    spread_main_loop
	TESTQ R12, R12
	JZ    spread_check_ok
	MOVQ  ctx+8(FP), AX
	MOVQ  R12, 32(AX)
	MOVQ  $+1, ret+16(FP)
	RET

spread_check_ok:
	// Build Decoding table
	XORQ R8, R8

build_table_main_table:
	MOVBQZX 1(SI)(R8*8), R9
	MOVWQZX (BX)(R9*2), R10
	LEAQ    1(R10), CX
	MOVW    CX, (BX)(R9*2)
	MOVQ    R10, R11
	BSRQ    R11, R11
	MOVQ    DX, CX
	SUBQ    R11, CX
	SHLQ    CL, R10
	SUBQ    AX, R10
	MOVQ    (DI)(R9*8), R9
	ORQ     CX, R9
	MOVQ    R10, R11
	ANDQ    $0x0000ffff, R11
	SHLQ    $0x10, R11
	ORQ     R11, R9
	MOVQ    R9, (SI)(R8*8)
	CMPQ    R10, AX
	JLE     build_table_check1_ok
	MOVQ    ctx+8(FP), CX
	MOVQ    R10, 32(CX)
	MOVQ    AX, 40(CX)
	MOVQ    $+2, ret+16(FP)
	RET

build_table_check1_ok:
	TESTB CL, CL
	JNZ   build_table_check2_ok
	CMPW  R10, R8
	JNE   build_table_check2_ok
	MOVQ  ctx+8(FP), AX
	MOVQ  R10, 32(AX)
	MOVQ  R8, 40(AX)
	MOVQ  $+3, ret+16(FP)
	RET

build_table_check2_ok:
	INCQ R8
	CMPQ R8, AX
	JL   build_table_main_table
	MOVQ $+0, ret+16(FP)
	RET
